
version: '3'
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - ./MySQL/init.sql:/docker-entrypoint-MySQL.d/0_init.sql
    environment:
      - PORT=3000